<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', static function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin/')->middleware(['auth'])->name('admin.')->group(static function(){
    Route::prefix('access/')->name('access.')->group( static function () {
        
    /*
    *Start Web Routes For UserController   Generated By Crud Generator  At Friday 26th of April 2019 03:27:13 PM
    */
        Route::get('/users/index',  'UserController@index')->name('users.index');
        Route::get('/users/create',  'UserController@create')->name('users.create');
        Route::post('/users/store',  'UserController@store')->name('users.store');
        Route::get('/users/{user}/show',  'UserController@show')->name('users.show');
        Route::get('/users/{user}/edit',  'UserController@edit')->name('users.edit');
        Route::put('/users/{user}/update',  'UserController@update')->name('users.update');
        Route::delete('/users/{user}/delete',  'UserController@destroy')->name('users.destroy');
    /*
    *End Web Routes For UserController
    */

    /*
    *Start Web Routes For UserController   Generated By Crud Generator  At Friday 26th of April 2019 03:27:13 PM
    */
        Route::get( '/roles/index',  'UserController@index')->name( 'roles.index');
        Route::get('/roles/create',  'UserController@create')->name( 'roles.create');
        Route::post( '/roles/store',  'UserController@store')->name( 'roles.store');
        Route::get('/roles/{role}/show',  'UserController@show')->name( 'roles.show');
        Route::get( '/roles/{role}/edit',  'UserController@edit')->name( 'roles.edit');
        Route::put( '/roles/{role}/update',  'UserController@update')->name( 'roles.update');
        Route::delete( '/roles/{role}/delete',  'UserController@destroy')->name( 'roles.destroy');
    /*
    *End Web Routes For UserController
    */

        Route::resource('permissions', 'PermissionController');
    });
});
